name: Cherry Pick Desixtification Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UN1CA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add source repo
        run: |
          git remote add source https://github.com/adityaexperimental-1087/ExtremeROM-Lite-e2sxxx.git
          git fetch source sixteen

      - name: Cherry-pick commit
        run: |
          git cherry-pick 2ae3b83041aea93fb4a927dc056246ae7b06db98 || true

      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git push
